version: '3.8'

services:
  treinamento:
    build: .
    container_name: treinamento_mlops
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - .:/app
    command: python src/main.py